language: php
php:
    - 5.5
    - 5.6
    - 7
    - hhvm
matrix:
    allow_failures:
        -
            php: hhvm
cache:
    directories:
        - $HOME/.composer/cache
sudo: false
install:
    - 'travis_retry composer global require "fabpot/php-cs-fixer:*" "phpunit/phpunit-skeleton-generator:*" "phpunit/phpunit:^4.8"'
    - 'travis_retry composer install --no-interaction'
    - './vendor/bin/hidev travis/install'
script:
    - './vendor/bin/hidev travis/script'
after_script:
    - './vendor/bin/hidev travis/after_script'
