vendor:
    name:       hiqdev
    title:      HiQDev
    github:     https://github.com/hiqdev
    homepage:   http://hiqdev.com/
    forum:      http://forum.hiqdev.com/
    email:      support@hiqdev.com
    license:    BSD-3-Clause
    authors:
        hiqsol:
            name:       Andrii Vasyliev
            role:       Project lead
            email:      sol@hiqdev.com
            github:     https://github.com/hiqsol
            homepage:   http://hipanel.com/
        SilverFire:
            name:       Dmitry Naumenko
            role:       Lead backend developer
            email:      d.naumenko.a@gmail.com
            github:     https://github.com/SilverFire
            homepage:   http://silverfire.me/
        tafid:
            name:       Andrey Klochok
            role:       Lead frontend developer
            email:      andreyklochok@gmail.com
            github:     https://github.com/tafid
            homepage:   http://hiqdev.com/
        BladeRoot:
            name:       Yuriy Myronchuk
            role:       QA Lead
            email:      bladeroot@gmail.com
            github:     https://github.com/BladeRoot
            homepage:   http://hiqdev.com/

default:
    before:
        - README.md
.php_cs:
    level: symfony
    header: |
        {{ config.package.title }}

        @link      {{ config.package.homepage }}
        @package   {{ config.package.name }}
        @license   {{ config.package.license }}
        @copyright Copyright (c) {{ config.package.years }}, {{ config.vendor.titleAndHomepage }}
    fixers:
        header_comment:                         |       # Add, replace or remove header comment
            [
                'header'        => $header,
                'separate'      => 'bottom',
                'location'      => 'after_declare_strict',
                'commentType'   => 'PHPDoc',
            ]
        binary_operator_spaces:                 |       # Align double arrow symbols in consecutive lines
            [
                'default' => null,
            ]
        concat_space:                           |       # Concatenation should be spaced according configuration
            ['spacing' => 'one']
        array_syntax:                           |       # PHP arrays should use the PHP 5.4 short-syntax
            ['syntax' => 'short']
        phpdoc_no_alias_tag:                    |       # No alias PHPDoc tags should be used
            ['replacements' => ['type' => 'var']]
        blank_line_before_return:               false   # An empty line feed should precede a return statement
        phpdoc_align:                           false   # All items of the @param, @throws, @return, @var, and @type phpdoc tags must be aligned vertically
        phpdoc_summary:                         false   # PHPDoc summary should end in either a full stop, exclamation mark, or question mark
        phpdoc_scalar:                          false   # Scalar types should always be written in the same form. "int", not "integer"; "bool", not "boolean"
        phpdoc_separation:                      false   # Annotations of a different type are separated by a single blank line
        phpdoc_to_comment:                      false   # Docblocks should only be used on structural elements
        phpdoc_var_without_name:                false   # @var and @type annotations should not contain the variable name.
        method_argument_space:                  false   # In method arguments and method call, there MUST NOT be a space before each comma and there MUST be one space after each comma
        ereg_to_preg:                           true    # Replace deprecated ereg regular expression functions with preg. Warning! This could change code behavior
        blank_line_after_opening_tag:           true    # Ensure there is no code on the same line as the PHP open tag and it is followed by a blankline
        single_blank_line_before_namespace:     true    # There should be no blank lines before a namespace declaration
        ordered_imports:                        true    # Ordering use statements
        phpdoc_order:                           true    # Annotations in phpdocs should be ordered so that @param come first, then @throws, then @return
        pre_increment:                          true    # Pre incrementation/decrementation should be used if possible
        strict_comparison:                      true    # Comparison should be strict. (Risky fixer!)
        strict_param:                           true    # Functions should be used with $strict param. Warning! This could change code behavior
        no_multiline_whitespace_before_semicolons: true # Multi-line whitespace before closing semicolon are prohibited
        semicolon_after_instruction: false
        yoda_style: null
    finder:
        notPath:
            - vendor
            - runtime
            - web/assets
            - public/assets
            - tests/_support/_generated

behat:
    colors: true
