package:
    name:           hidev-hiqdev
    namespace:      hidev\hiqdev
    headline:       HiDev HiQDev
    title:          HiQDev vendor configuration for HiDev
    type:           yii2-extension
    keywords:       hiqdev, hidev, config
    year:           2015
    description:    |
        [HiDev](https://github.com/hiqdev/hidev) is a task runner, code generator and build tool for easier continuos integration.
        This plugin provides [HiQDev](https://github.com/hiqdev) vendor configuration for HiDev.
        Used for HiQDev packages. Can be used as template for configs of other vendors.

        Provides HiQDev information and settings:
        * general data: vendor name and company title
        * contact data: email, forum, github page
        * authors data: names, roles, emails, github and home pages
        * default license: BSD-3-Clause

        See [src/config.yml](src/config.yml).

include:
    - src/config.yml

require:
    hiqdev/hidev-php:           "*@dev"
    hiqdev/hidev-license:       "*@dev"
    hiqdev/hidev-phpunit:       "*@dev"
    hiqdev/hidev-travis-ci:     "*@dev"
    hiqdev/hidev-codeception:   "*@dev"
    hiqdev/hidev-php-cs-fixer:  "*@dev"

